//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIHelpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIHelpers.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By vault access rights.
        /// </summary>
        internal static string AccessRestrictionType_ByVaultRights {
            get {
                return ResourceManager.GetString("AccessRestrictionType_ByVaultRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AccessRestrictionType_Custom {
            get {
                return ResourceManager.GetString("AccessRestrictionType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Restriction Type.
        /// </summary>
        internal static string AccessRestrictionType_Label {
            get {
                return ResourceManager.GetString("AccessRestrictionType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced_Label {
            get {
                return ResourceManager.GetString("Advanced_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed User Groups.
        /// </summary>
        internal static string AllowedUserGroups_Label {
            get {
                return ResourceManager.GetString("AllowedUserGroups_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Users.
        /// </summary>
        internal static string AllowedUsers_Label {
            get {
                return ResourceManager.GetString("AllowedUsers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConfiguredLocations_HelpText {
            get {
                return ResourceManager.GetString("ConfiguredLocations_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed locations.
        /// </summary>
        internal static string ConfiguredLocations_Label {
            get {
                return ResourceManager.GetString("ConfiguredLocations_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultLocation_HelpText {
            get {
                return ResourceManager.GetString("DefaultLocation_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default location.
        /// </summary>
        internal static string DefaultLocation_Label {
            get {
                return ResourceManager.GetString("DefaultLocation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing.
        /// </summary>
        internal static string EnableEditing_Label {
            get {
                return ResourceManager.GetString("EnableEditing_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Languages_ChildName {
            get {
                return ResourceManager.GetString("Languages_ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages_Label {
            get {
                return ResourceManager.GetString("Languages_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under the listing.
        /// </summary>
        internal static string Location_BottomPane {
            get {
                return ResourceManager.GetString("Location_BottomPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab on right.
        /// </summary>
        internal static string Location_NewTab {
            get {
                return ResourceManager.GetString("Location_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a pop-out window.
        /// </summary>
        internal static string Location_PopOut {
            get {
                return ResourceManager.GetString("Location_PopOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Access Rights.
        /// </summary>
        internal static string RequiredAccessRights_Label {
            get {
                return ResourceManager.GetString("RequiredAccessRights_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Preview.
        /// </summary>
        internal static string ShowPreview_Label {
            get {
                return ResourceManager.GetString("ShowPreview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown on the &quot;close&quot; button in the dashboard.
        /// </summary>
        internal static string UI_Commands_Buttons_Close_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Close_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (button).
        /// </summary>
        internal static string UI_Commands_Buttons_Close_Label {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Close_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown on the &quot;discard&quot; button in the dashboard.
        /// </summary>
        internal static string UI_Commands_Buttons_Discard_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Discard_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard (button).
        /// </summary>
        internal static string UI_Commands_Buttons_Discard_Label {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Discard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown on the &quot;save&quot; button in the dashboard.
        /// </summary>
        internal static string UI_Commands_Buttons_Save_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Save_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (button).
        /// </summary>
        internal static string UI_Commands_Buttons_Save_Label {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Save_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command button text, shown in the context menu.
        /// </summary>
        internal static string UI_Commands_ShowAllMetadata_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowAllMetadata_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all metadata (Command text).
        /// </summary>
        internal static string UI_Commands_ShowAllMetadata_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowAllMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown when hovering over the &quot;show below listing&quot; icon.
        /// </summary>
        internal static string UI_Commands_ShowBelowListing_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowBelowListing_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show below listing.
        /// </summary>
        internal static string UI_Commands_ShowBelowListing_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowBelowListing_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown when hovering over the &quot;show in a pop-up window&quot; icon.
        /// </summary>
        internal static string UI_Commands_ShowInPopOutWindow_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowInPopOutWindow_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in a pop-up window.
        /// </summary>
        internal static string UI_Commands_ShowInPopOutWindow_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowInPopOutWindow_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown when hovering over the &quot;show in tab on the right&quot; icon.
        /// </summary>
        internal static string UI_Commands_ShowInTabOnRight_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowInTabOnRight_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in tab on right.
        /// </summary>
        internal static string UI_Commands_ShowInTabOnRight_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowInTabOnRight_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UI_Commands_ShowPreview_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowPreview_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preview (Command text).
        /// </summary>
        internal static string UI_Commands_ShowPreview_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowPreview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UI_TabTitles_RawMetadata_HelpText {
            get {
                return ResourceManager.GetString("UI_TabTitles_RawMetadata_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab title (Raw metadata).
        /// </summary>
        internal static string UI_TabTitles_RawMetadata_Label {
            get {
                return ResourceManager.GetString("UI_TabTitles_RawMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UI_TabTitles_ShowPreview_HelpText {
            get {
                return ResourceManager.GetString("UI_TabTitles_ShowPreview_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab title (Show preview).
        /// </summary>
        internal static string UI_TabTitles_ShowPreview_Label {
            get {
                return ResourceManager.GetString("UI_TabTitles_ShowPreview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Configuration.
        /// </summary>
        internal static string UserConfiguration_Label {
            get {
                return ResourceManager.GetString("UserConfiguration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Metadata.
        /// </summary>
        internal static string ViewAllMetadata_Label {
            get {
                return ResourceManager.GetString("ViewAllMetadata_Label", resourceCulture);
            }
        }
    }
}
