//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewAllMetadata.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewAllMetadata.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By vault access rights.
        /// </summary>
        internal static string AccessRestrictionType_ByVaultRights {
            get {
                return ResourceManager.GetString("AccessRestrictionType_ByVaultRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AccessRestrictionType_Custom {
            get {
                return ResourceManager.GetString("AccessRestrictionType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Restriction Type.
        /// </summary>
        internal static string AccessRestrictionType_Label {
            get {
                return ResourceManager.GetString("AccessRestrictionType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced_Label {
            get {
                return ResourceManager.GetString("Advanced_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed User Groups.
        /// </summary>
        internal static string AllowedUserGroups_Label {
            get {
                return ResourceManager.GetString("AllowedUserGroups_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Users.
        /// </summary>
        internal static string AllowedUsers_Label {
            get {
                return ResourceManager.GetString("AllowedUsers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Languages_ChildName {
            get {
                return ResourceManager.GetString("Languages_ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Languages_Label {
            get {
                return ResourceManager.GetString("Languages_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Access Rights.
        /// </summary>
        internal static string RequiredAccessRights_Label {
            get {
                return ResourceManager.GetString("RequiredAccessRights_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text shown on the &quot;close&quot; button in the dashboard.
        /// </summary>
        internal static string UI_Commands_Buttons_Close_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Close_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string UI_Commands_Buttons_Close_Label {
            get {
                return ResourceManager.GetString("UI_Commands_Buttons_Close_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command button text, shown in the context menu.
        /// </summary>
        internal static string UI_Commands_ShowAllMetadata_HelpText {
            get {
                return ResourceManager.GetString("UI_Commands_ShowAllMetadata_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all metadata.
        /// </summary>
        internal static string UI_Commands_ShowAllMetadata_Label {
            get {
                return ResourceManager.GetString("UI_Commands_ShowAllMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Configuration.
        /// </summary>
        internal static string UserConfiguration_Label {
            get {
                return ResourceManager.GetString("UserConfiguration_Label", resourceCulture);
            }
        }
    }
}
